### ISSUE TITLE
[Feature request / Question] Alternative way to notify end users about issues 

### ISSUE THREAD

**Issue by andriy-baran** [fatkodima/columns_trace#1]
Hi,

Thanks for developing this gem, I found this gem very useful.
To my mind log file is a good way to communicate issues. 
I wanted to improve the management of reported issues (like resolving, skipping, UI)
I was able to implement is by parsing a log file and storing them in database.
It would be nice to have something like [ActiveSupport::Notifications](https://guides.rubyonrails.org/active_support_instrumentation.html#creating-custom-events) for the reporting purpose.
In my case it will replace log file parsing (which is not scalable) and maybe will allow to ignore issues I'm not intended to fix (like some things in layout, that are common to many pages)

What do you think?

Thanks

**Comment by fatkodima** [comment]
Hi, I'm happy you find it useful! 

> I wanted to improve the management of reported issues (like resolving, skipping, UI)

Can you give more details about your use case?

**Comment by andriy-baran** [comment]
In development mode I want to build an UI with following features
* ability to list distinct issues 
* ability to sort / filter issues 
* mark issue as resolved or ignored 

Based on your work I created the following model
```ruby
  create_table :column_trace_records do |t|
      t.string :action
      t.integer :count
      t.string :model
      t.text :used
      t.text :unused
      t.text :backtrace
      t.boolean :resolved
      t.index [:model, :used, :backtrace], name: 'issue_idx', unique: true
    end
```

And ability to subscribe to events stream and create / update these records would simplify my implementation

**Comment by fatkodima** [comment]
I think, `ActiveSupport::Notifications` is not necessarily needed in this case. I can create something like "reporters", where you can specify your custom reporter. It will be passed all the details like backtrace, used/unused columns etc. With the logger reporter as a default one, to mimic the current behaviour.

I did something similar in my other gem - https://github.com/fatkodima/data_checks/tree/master/lib/data_checks/notifiers. In that case it is named "notifiers", but the concept is the same.

Wdyt?

**Comment by andriy-baran** [comment]
I like this concept.

**Comment by fatkodima** [comment]
Ok, I will look then into it. If you would like to work on a PR by yourself, please let me know.

**Comment by fatkodima** [comment]
Release a new version with this change.
